services:
  ts-casawasm-app:
    image: tailscale/tailscale:latest
    container_name: ts-casawasm-bff
    hostname: casa-pahampang-webapp
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "tailscaled & 
             sleep 5; 
             tailscale up --authkey=$$TS_AUTHKEY --hostname=casa-pahampang-webapp;             
             tailscale funnel --bg 8080; 
             wait"
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./ts-state:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always

  my-wasm-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    container_name: casawasm-bff-container
    user: "root"
    restart: always
    network_mode: "service:ts-casawasm-app" 
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=pahampangdb;Username=postgres;Password=${DB_PASSWORD}
      - AuthApiBaseUrl=https://casa-authgateway-service.taila207b7.ts.net
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=https://casa-authgateway-service.taila207b7.ts.net
      - Jwt__Audience=https://casa-authgateway-service.taila207b7.ts.net      

    volumes:
      - ./pr-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - ts-casawasm-app